name: Security & Quality Scan
on: 
  push:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Build
        run: ./gradlew build -x test
      
      # SonarCloud avec action officielle
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.java.binaries=build/classes
      
      # Snyk Scan
      - name: Install & Run Snyk
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --json-file-output=snyk-report.json || true
          snyk monitor --project-name="${{ github.repository }}"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-report
          path: snyk-report.json