name: Security Scan
on: 
  push:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Build
        run: ./gradlew build -x test
      
      - name: Install & Run Snyk
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --json-file-output=snyk-report.json || true
          snyk monitor --project-name="${{ github.repository }}"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-report
          path: snyk-report.json