name: Security Scan with Reporting
on: 
  push:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
      # Export vers JSON
      - name: Generate Snyk report
        run: |
          snyk test --json > snyk-report.json || true
          snyk monitor  
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}