name: Security Scan with Reporting
on: 
  push:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Setup Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      
      # Utiliser l'action Snyk avec arguments
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        with:
          args: --json-file-output=snyk-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      # Setup Snyk pour monitor
      - name: Setup Snyk
        uses: snyk/actions/setup@master
      
      # Monitor project
      - name: Snyk Monitor
        continue-on-error: true
        run: snyk monitor --project-name="${{ github.repository }}"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      # Upload rapport
      - name: Upload Snyk Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-report
          path: snyk-report.json
          retention-days: 30